# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500

  # Motivation for the extra joints added to the joint_state_controller: https://github.com/ros-controls/ros_controllers/issues/87
  extra_joints:
    - name: gripper_r_joint
      position: 0.0
    - name: gripper_l_joint
      position: 0.0


# Effort gripper position controllers ---------------------------------------
gripper_effort_pos_controller_r:
  type: effort_controllers/JointPositionController
  joint: gripper_r_joint
  pid: {p: 0.1, i: 0.01, d: 0.1, i_clamp_min: -1, i_clamp_max: 1}

gripper_effort_pos_controller_l:
  type: effort_controllers/JointPositionController
  joint: gripper_l_joint
  pid: {p: 0.1, i: 0.01, d: 0.1, i_clamp_min: -1, i_clamp_max: 1}




# Joint Trajectory Position Controlles ----------------------------------------
joint_traj_pos_controller_l:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - yumi_joint_1_l
    - yumi_joint_2_l
    - yumi_joint_7_l
    - yumi_joint_3_l
    - yumi_joint_4_l
    - yumi_joint_5_l
    - yumi_joint_6_l

joint_traj_pos_controller_r:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - yumi_joint_1_r
    - yumi_joint_2_r
    - yumi_joint_7_r
    - yumi_joint_3_r
    - yumi_joint_4_r
    - yumi_joint_5_r
    - yumi_joint_6_r


# Joint Trajectory Velocity Controller ----------------------------------------
joint_traj_vel_controller_l:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - yumi_joint_1_l
    - yumi_joint_2_l
    - yumi_joint_7_l
    - yumi_joint_3_l
    - yumi_joint_4_l
    - yumi_joint_5_l
    - yumi_joint_6_l
  gains:
    yumi_joint_1_l: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    yumi_joint_2_l: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    yumi_joint_7_l: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    yumi_joint_3_l: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    yumi_joint_4_l: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    yumi_joint_5_l: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    yumi_joint_6_l: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}



joint_traj_vel_controller_r:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - yumi_joint_1_r
    - yumi_joint_2_r
    - yumi_joint_7_r
    - yumi_joint_3_r
    - yumi_joint_4_r
    - yumi_joint_5_r
    - yumi_joint_6_r
  gains:
    yumi_joint_1_r: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    yumi_joint_2_r: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    yumi_joint_7_r: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    yumi_joint_3_r: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    yumi_joint_4_r: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    yumi_joint_5_r: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    yumi_joint_6_r: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
